name: Deploy to Staging

on: [push]

jobs:
  # Arbitrary Job Section Name (Won't be Displayed)
  deploy:
    # Operating System to Run the Script On
    runs-on: ubuntu-latest
    # Job Name (Will be Displayed)
    name: Deploy to Staging
    steps:
      # Step Name
      - name: Set up SSH
        # Run Miltiline Bash Script
        run: |
          mkdir -p ~/.ssh
          echo ${{secrets.GIT_CONFIG}} > ~/.ssh/config
          echo ${{secrets.SSH_KEY_STAGING}} > ~/.ssh/stageKey
          echo ${{secrets.SSH_KEY_GITHUB_ACCESS}} > ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/stageKey
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/GitKey
          echo "${{secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts
        # Shell Type
        shell: bash

      # Step Name
      - name: Install PM2
        # Single-Line Bash Script
        run: sudo npm i -g pm2 &>/dev/null
        # Shell Type
        shell: bash

      # Step Name
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pm2
        with:
          path: /usr/lib/node_modules/pm2
          key: 123456
          restore-keys: 123456

      # Step Name
      - name: Running Deployment Script
        # Run Miltiline Bash Script
        run: |
          git clone git@github.com:knct-app/back-end.git
          cd back-end
          echo "$secrets.ECOSYSTEM_FILE" > ./miscConfig/ecosystem.json
          cd miscConfig
          npm run deploy
        # Shell Type
        shell: bash
